# Generated by Django 5.2.9 on 2026-04-02 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_pricingplan_historicalpricingplan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpricingplan',
            name='features',
        ),
        migrations.RemoveField(
            model_name='pricingplan',
            name='features',
        ),
        migrations.CreateModel(
            name='PricingFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('is_available', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='payments.pricingplan')),
            ],
            options={
                'verbose_name': 'Pricing Feature',
                'verbose_name_plural': 'Pricing Features',
                'ordering': ['sort_order'],
            },
        ),
    ]
