volumes:
  instarchiver_production_postgres_data: {}
  instarchiver_production_postgres_data_backups: {}
  instarchiver_production_traefik: {}
  instarchiver_production_django_media: {}
  instarchiver_production_redis_data: {}


services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile

    image: instarchiver_production_django
    restart: unless-stopped
    mem_limit: 512m
    volumes:
      - instarchiver_production_django_media:/app/core/media
    depends_on:
      - pgbouncer
      - redis
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: instarchiver_production_postgres
    restart: unless-stopped
    ports:
      - 100.73.60.108:65432:5432
    volumes:
      - instarchiver_production_postgres_data:/var/lib/postgresql/data
      - instarchiver_production_postgres_data_backups:/backups
    env_file:
      - ./.envs/.production/.postgres

  pgbouncer:
    image: edoburu/pgbouncer:latest
    container_name: instarchiver_production_pgbouncer
    restart: unless-stopped
    env_file:
      - ./.envs/.production/.postgres
    environment:
      - DB_HOST=postgres
      - AUTH_TYPE=scram-sha-256
      - POOL_MODE=transaction
    depends_on:
      - postgres
    healthcheck:
      test: ['CMD', 'pg_isready', '-h', 'localhost']
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: docker.io/redis:6
    restart: unless-stopped
    volumes:
      - instarchiver_production_redis_data:/data
    ports:
      - 100.73.60.108:64202:6379


  celeryworker:
    <<: *django
    image: instarchiver_production_celeryworker
    mem_limit: 384m
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: instarchiver_production_celerybeat
    command: /start-celerybeat

  flower:
    <<: *django
    image: instarchiver_production_flower
    mem_limit: 256m
    command: /start-flower

  nginx:
    build:
      context: .
      dockerfile: ./compose/production/nginx/Dockerfile
    image: instarchiver_production_nginx
    restart: unless-stopped
    depends_on:
      - django
    volumes:
      - instarchiver_production_django_media:/usr/share/nginx/media:ro
    ports:
      - 100.73.60.108:64001:80

  awscli:
    build:
      context: .
      dockerfile: ./compose/production/aws/Dockerfile
    image: instarchiver_production_awscli
    env_file:
      - ./.envs/.production/.django
    volumes:
      - instarchiver_production_postgres_data_backups:/backups:z
