# Generated by Django 5.2.9 on 2026-04-20 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0009_stripesetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenRouterSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding_api_key', models.CharField(blank=True, default='', help_text='OpenRouter API Key for embeddings', max_length=255)),
                ('embedding_base_url', models.URLField(default='https://openrouter.ai/api/v1/embeddings', help_text='OpenRouter Embeddings endpoint URL', max_length=255)),
                ('image_embedding_model', models.CharField(blank=True, default='nvidia/llama-nemotron-embed-vl-1b-v2', help_text='Model for image embeddings', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'OpenRouter Setting',
            },
        ),
    ]
