# Generated by Django 5.2.9 on 2026-09-23 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0010_openroutersetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='coreapisetting',
            name='saveapi_api_key',
            field=models.CharField(blank=True, default='', help_text='SaveAPI API key', max_length=255),
        ),
        migrations.AddField(
            model_name='coreapisetting',
            name='saveapi_url',
            field=models.URLField(blank=True, default='', help_text='SaveAPI base URL', max_length=255),
        ),
    ]
