# Generated by Django 5.2.9 on 2026-09-24 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0011_coreapisetting_saveapi_api_key_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_token', models.CharField(blank=True, default='', help_text='Telegram bot token from BotFather', max_length=255)),
                ('webhook_secret', models.CharField(blank=True, default='', help_text='Secret Telegram sends in the X-Telegram-Bot-Api-Secret-Token header. Allowed characters: A-Z, a-z, 0-9, _ and -', max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Telegram Setting',
            },
        ),
    ]
