#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

if [ -z "${POSTGRES_USER}" ]; then
    base_postgres_image_default_user='postgres'
    export POSTGRES_USER="${base_postgres_image_default_user}"
fi

# Use PgBouncer when PGBOUNCER_HOST and PGBOUNCER_PORT are set,
# otherwise connect directly to PostgreSQL.
if [ -n "${PGBOUNCER_HOST:-}" ] && [ -n "${PGBOUNCER_PORT:-}" ]; then
    export DATABASE_URL="postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${PGBOUNCER_HOST}:${PGBOUNCER_PORT}/${POSTGRES_DB}"
    wait-for-it "${PGBOUNCER_HOST}:${PGBOUNCER_PORT}" -t 30
    >&2 echo 'PgBouncer is available'
else
    export DATABASE_URL="postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}"
    wait-for-it "${POSTGRES_HOST}:${POSTGRES_PORT}" -t 30
    >&2 echo 'PostgreSQL is available'
fi

exec "$@"
