#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

if [ -z "${POSTGRES_USER}" ]; then
    base_postgres_image_default_user='postgres'
    export POSTGRES_USER="${base_postgres_image_default_user}"
fi

# Route through pgbouncer if configured, otherwise connect directly to postgres
DB_HOST="${PGBOUNCER_HOST:-${POSTGRES_HOST}}"
DB_PORT="${PGBOUNCER_PORT:-${POSTGRES_PORT}}"

export DATABASE_URL="postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${DB_HOST}:${DB_PORT}/${POSTGRES_DB}"

wait-for-it "${DB_HOST}:${DB_PORT}" -t 30

>&2 echo 'Database is available'

exec "$@"
