#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


python /app/manage.py collectstatic --noinput

exec /usr/local/bin/gunicorn config.asgi:application --bind 0.0.0.0:5000 --chdir=/app -k uvicorn_worker.UvicornWorker --workers 2 --max-requests 1000 --max-requests-jitter 50 --worker-tmp-dir /dev/shm
