# Generated by Django 5.2.9 on 2026-03-31 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0032_story_embedding_story_embedding_token_usage'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='story',
            name='moderated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='moderation_result',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
