# Generated by Django 5.2.9 on 2026-03-31 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0033_story_is_flagged_story_moderated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpost',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalpost',
            name='moderated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalpost',
            name='moderation_result',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='moderated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='moderation_result',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
