# Generated by Django 5.2.9 on 2026-04-06 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0034_historicalpost_is_flagged_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_set', to='instagram.user')),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower_set', to='instagram.user')),
            ],
            options={
                'indexes': [models.Index(fields=['follower', 'is_active'], name='instagram_u_followe_6c5e54_idx'), models.Index(fields=['following', 'is_active'], name='instagram_u_followi_7fc244_idx')],
                'unique_together': {('follower', 'following')},
            },
        ),
    ]
